### ISSUE TITLE
pretrained model file corrupted?

### ISSUE THREAD

**Issue by wdrink** [erprogs/CViT#1]
Hello, when I want to test your code and pretrained model on my datasaet, I occurred the error " RuntimeError: Invalid magic number; corrupt file?", I guess the pretrained model file that you provide is corrupted. BTW, I couldn't find the detection model file.

**Comment by erprogs** [comment]
Hello Junke, 
Sorry for the inconvenience. There are two pre-trained files that I have released. Both files work fine on my system. "deepfake_cvit_gpu_inference_ep_50.pth" file is used only for prediction whereas "deepfake_cvit_gpu_ep_50.pth" can be used for both training and prediction.

Can you show me your code that triggered the error? Thank you.

**Comment by wdrink** [comment]
> Hello Junke, Sorry for the inconvenience. There are two pre-trained files that I have released. Both files work fine on my system. "deepfake_cvit_gpu_inference_ep_50.pth" file is used only for prediction whereas "deepfake_cvit_gpu_ep_50.pth" can be used for both training and prediction. Can you show me your code that triggered the error? Thank you.

I'm sorry that I could find 'deepfake_cvit_gpu_inference_ep_50.pth' file, and I just use your code for inference.

**Comment by erprogs** [comment]
You can get the files from here: https://github.com/erprogs/CViT/releases/tag/v1.0

Can you share the code that caused the error?

**Comment by wdrink** [comment]
> You can get the files from here: https://github.com/erprogs/CViT/releases/tag/v1.0
> 
> Can you share the code that caused the error?

Hi, using the model files in your release, I successfully run the code! Thanks a lot. BTW, is the model you provide is trained on FF++?

**Comment by erprogs** [comment]
Great!. The model is trained using DFDC. FF++ is used to test the model.

**Comment by wdrink** [comment]
> Great!. The model is trained using DFDC. FF++ is used to test the model.

Alright. Thanks a lot again for your amazing work.
