### ISSUE TITLE
how to get Dfdc label? 

### ISSUE THREAD

**Issue by wangtao2668129173** [erprogs/CViT#10]
Thank you for your work. I'll continue training，I already have 50 compressed videos, but I don't know how to get labels？

**Comment by erprogs** [comment]
Hello @wangtao2668129173, 
if you are using the [DFDC ](https://www.kaggle.com/c/deepfake-detection-challenge/data) dataset, you can use the [preprocessing](https://github.com/erprogs/CViT/blob/main/preprocessing/extractfaces.py) code. 
Or 
you can create two folders like this: <br/>
&nbsp;&nbsp; &nbsp;&nbsp; train<br/>
&nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; real<br/>
&nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; fake<br/>
&nbsp;&nbsp; &nbsp;&nbsp; valid<br/>
&nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; real<br/>
&nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; fake<br/>
and put your images in sub-folders real & fake.

**Comment by erprogs** [comment]
When you load the datasets for training, your folders (real & fake) become your labels. Happy coding!
