### ISSUE TITLE
How is the feature map of the FL component divided into 7 patches?

### ISSUE THREAD

**Issue by gwxdlut** [erprogs/CViT#11]
hello @erprogs ,Sorry for bothering you!
I have some confusion about how to divide the convolutional feature map into 7 patches.The size of a picture after being processed by the FL component is (512, 7, 7). According to the description in the paper, it is divided into 7 patches, but your code does not seem to divide the feature map. The process is directly Convert the feature map from (512, 7, 7) to (1, 25088), and then map it to (1, 1024) through a linear layer, adding class token and position embedding. This seems to be inconsistent with the description in the paper. could you please help me understand the problem?

**Comment by erprogs** [comment]
Hello @gwxdlut,
Thank you for pointing that out. I think I've made a mistake with that statement. I was referring to this line of code, but it doesn't do as I described it in the paper. 
`y = rearrange(x, 'b c (h p1) (w p2) -> b (h w) (p1 p2 c)', p1 = p, p2 = p)
`

Sorry for the inconvenience. Thanks.
