### ISSUE TITLE
pretrained-weights

### ISSUE THREAD

**Issue by wuqile123456** [erprogs/CViT#14]
Could the author please provide these two files?
deepfake_cvit_gpu_ep_50.pth - Full model weight.
deepfake_cvit_gpu_inference_ep_50.pth - For detection.

**Comment by erprogs** [comment]
Here it is: found under "Weights for CViT"

https://github.com/erprogs/CViT/releases/tag/v1.0

**Comment by wuqile123456** [comment]
> 

oh,thank you!

**Comment by erprogs** [comment]
Great!
You can also check out our newest work in the area here: [GenConViT](https://github.com/erprogs/GenConViT)

**Comment by wuqile123456** [comment]
> 

Ok, I will read and learn from it. I tried CVit and it works great!

**Comment by erprogs** [comment]
Okay. Thank you.
