### ISSUE TITLE
  raise err OSError: [WinError 127] 找不到指定的程序。

### ISSUE THREAD

**Issue by xiaomo9** [erprogs/CViT#16]
First of all, thank you for publicizing this project, which can let me learn as a student. However, I have encountered some problems when running the program, and I hope you can answer them.

When I run the video extraction program:extractfaces.py

I reported this error:  raise err
OSError: [WinError 127] 找不到指定的程序。 Error loading "E:\BIANCHENG\Anaconda\envs\pytorch\lib\sitepackages\torch\lib\cudnn_adv_infer64_8.dll" or one of its dependencies.

Can you give me some advice? Thank you very much

**Comment by erprogs** [comment]
Thank you for testing our model.

The error is that the program is unable to locate cuDNN. Check if Cuda is correctly installed. Set the path of your cuDNN in the environmental variables. 

You can also change this line and run the code without cuda. (line 79)

`gpu = torch.device("cuda" if torch.cuda.is_available() else "cpu")` 
change it to 
`gpu ="cpu"`

**Comment by xiaomo9** [comment]
> Thank you for testing our model.
> 
> The error is that the program is unable to locate cuDNN. Check if Cuda is correctly installed. Set the path of your cuDNN in the environmental variables.
> 
> You can also change this line and run the code without cuda. (line 79)
> 
> `gpu = torch.device("cuda" if torch.cuda.is_available() else "cpu")` change it to `gpu ="cpu"`

Thank you for your answer. The problem has been solved and the cuda environment has been reconfigured. The previous environment may be damaged
