### ISSUE TITLE
preprocessing uses extractfaces.py for video face extraction

### ISSUE THREAD

**Issue by xiaomo9** [erprogs/CViT#17]
Thank you for your sharing, your work is very helpful to me, but I have a problem when learning this method, I hope you can answer it.

When preprocessing uses extractfaces.py for video face extraction, there are thousands of videos in the video data set. Why does this.py program only extractfaces from some videos while others do not? A dataset of 1,335 videos ended up extracting only 1,200 images, many of which were frames taken from the same video.
I am looking forward to your answer, thanks a lot!

**Comment by erprogs** [comment]
Thank you!,
I don't understand what 'this.py' is referring to. Can you elaborate? And which dataset are you trying to extract?

**Comment by xiaomo9** [comment]
> 谢谢！， 我不明白“this.py”指的是什么。你能详细说明一下吗？您想要提取哪个数据集？

extractfaces.py this program   Using this program to extract faces, I used dfdc_train_part_03 to verify the data set, and finally only extracted 1200 pictures, many videos were not manipulated
