### ISSUE TITLE
cvit-main and cvit-1.0 without environment  requirement.txt 

### ISSUE THREAD

**Issue by 18590286257** [erprogs/CViT#5]
Hi, thanks for your sharing. I can't run your code both your cvit-mian and cvit-1.0.
Question1:when I run cvit_prediction.py in cvit-main with the deepfake_cvit_gpu_inference_ep_50.pth, it reported:
0017_fake.mp4.mp4
0045.mp4.mp4
0048_fake.mp4.mp4
28__talking_angry_couch.mp4.mp4
Segmentation fault (core dumped)

Question2:when I run cvit_prediction.py in cvit-main with the deepfake_cvit_gpu_ep_50.pth, it reported:
![image](https://user-images.githubusercontent.com/68067181/120267517-aca1b200-c2d6-11eb-90a6-7372b82bf906.png)

Question3:I used pytorch1.7 and python3.7,can you show your environment details for us?

Question4:deepfake_cvit_gpu_ep_50.pth and deepfake_cvit_gpu_inference_ep_50.pth are not the same.  So, if I train the model with cvit_train.py. How can I use this model with your cvit_prediction.py file?

Thanks a lot. Can you help me to build a full workspace? I am also a student, just use to learning,Thanks.

**Comment by erprogs** [comment]
Hello, Thanks for testing our model.
1. Segmentation fault error occurs when the system tries to access a memory area that's not available [(core_dump).](https://en.wikipedia.org/wiki/Core_dump) I assume the face extraction models failed to extract the face regions. But that should be fine because when there are no face regions, the model will return 0.5. 
To test the error, can you modify this line of code: `filenames = sorted([x for x in os.listdir(sample) if x[-4:] == ".mp4"])` to `filenames = sorted([x for x in os.listdir(sample) if x[-4:] == ".mp4"])[3:4]`. This will help us identify the problem with '28__talking_angry_couch.mp4.mp4' file.
Have you modified the code? Specially num_workers? I have the same error when I set `num_workers=4` before.
2. If you are using GPU, use this: `#checkpoint = torch.load('weight/deepfake_cvit_gpu_inference_ep_50.pth') # for GPU`
3. Environment: PyTorch 1.7.0, Python 3.7.9, GPU: Tesla P100-PCIE-16GB.
4. As you have said, deepfake_cvit_gpu_ep_50.pth and deepfake_cvit_gpu_inference_ep_50.pth are not the same. deepfake_cvit_gpu_ep_50.pth contains the full dump of the model weights and it can be used for training. deepfake_cvit_gpu_inference_ep_50.pth is used for prediction only. When you train your model with cvit_train.py, the model saves a new state into the weights folder. `torch.save(state, 'weight/cvit_deepfake_detection_v2.pth')`.  Then, you can use your new saved model `(vit_deepfake_detection_v2.pth)` for prediction.
5. Can you help me to build a full workspace?. If I understood it correctly, you want to reproduce our result? If so, we used the DFDC dataset for training. We extracted the face regions using extractfaces.py. The model is CViT.py.
6.  I hope this answers your questions. Keep on learning!

**Comment by Yasmineldemery** [comment]
@erprogs 
Hello,
I was also testing ur code and when I tried to train the model on my own, then running the prediction file using my own weights in the weight folder created after training I got this error. I'm using GPU and when  i use 
#checkpoint = torch.load('/content/drive/MyDrive/Bachelor/CViT/weight/deepfake_cvit_gpu_inference_ep_50.pth')#
it works however when i use 
#checkpoint = torch.load('/content/drive/MyDrive/Bachelor/CViT/weight/deepfakeweights_2.pth')#
which is the new weights file it gives me this error:
![Capture](https://user-images.githubusercontent.com/64609398/120320992-12943680-c2e3-11eb-96e2-5406cadda3f6.PNG)

can u please care to explain where is the problem

I used the following code in the training file in train_gpu loading the model where I only changed the names of the weights:
 # load best model weights
    model.load_state_dict(best_model_wts)
    with open('/content/drive/MyDrive/Bachelor/CViT/weight/deepfakeweights_2.pkl', 'wb') as f:
        pickle.dump([train_loss, train_accu, val_loss, val_accu], f)
    state = {'epoch': num_epochs+1, 
             'state_dict': model.state_dict(),
             'optimizer': optimizer.state_dict(),
             'min_loss':epoch_loss}
    torch.save(state, '/content/drive/MyDrive/Bachelor/CViT/weight/deepfakeweights_2.pth')
    test(model)
    return train_loss,train_accu,val_loss,val_accu, min_loss

**Comment by yeaars** [comment]
Hi, I am running your code for learning.

> And for question 1, I made some test.

when I modify this line of code: `filenames = sorted([x for x in os.listdir(sample) if x[-4:] == ".mp4"])` to ` filenames = sorted([x for x in os.listdir(sample) if x[-4:] == ".mp4"])[n:n+1]` (n = 0 to 1)， it all works without any bug. That means it's ok for every video.

And I found when I modify ` num_workers = N`, the code occurs Segmentation fault after N-th video.
For example, when I set `num_workers = 9` and  run cvit_prediction.py:
![sendpix0](https://user-images.githubusercontent.com/82205987/120320783-248ecd00-c315-11eb-86e6-7db31338dd6f.jpg)

> For qusetion 2, I know it works when I use `checkpoint = torch.load('/content/drive/MyDrive/Bachelor/CViT/weight/deepfake_cvit_gpu_inference_ep_50.pth') `.
 However, what should I do if I want to train my own net?  I met the same problem when I use ` deepfake_cvit_gpu_ep_50.pth`.

**Comment by 18590286257** [comment]
Thank you very much!
As you have said, the num_workers is 4 before, then I set it =1,the cvit_prediction.py can run with out error.
Thanks a lot. And I am reading your article 《Deepfake Video Detection Using Convolutional Vision Transformer》. From this article，I learned a lot. It is a very important work,thanks for your sharing again.

**Comment by erprogs** [comment]
> 
> 
> @erprogs
> Hello,
> I was also testing ur code and when I tried to train the model on my own, then running the prediction file using my own weights in the weight folder created after training I got this error. I'm using GPU and when i use
> #checkpoint = torch.load('/content/drive/MyDrive/Bachelor/CViT/weight/deepfake_cvit_gpu_inference_ep_50.pth')#
> it works however when i use
> #checkpoint = torch.load('/content/drive/MyDrive/Bachelor/CViT/weight/deepfakeweights_2.pth')#
> which is the new weights file it gives me this error:
> ![Capture](https://user-images.githubusercontent.com/64609398/120320992-12943680-c2e3-11eb-96e2-5406cadda3f6.PNG)
> 
> can u please care to explain where is the problem
> 
> I used the following code in the training file in train_gpu loading the model where I only changed the names of the weights:
> # load best model weights
> 
> ```
> model.load_state_dict(best_model_wts)
> with open('/content/drive/MyDrive/Bachelor/CViT/weight/deepfakeweights_2.pkl', 'wb') as f:
>     pickle.dump([train_loss, train_accu, val_loss, val_accu], f)
> state = {'epoch': num_epochs+1, 
>          'state_dict': model.state_dict(),
>          'optimizer': optimizer.state_dict(),
>          'min_loss':epoch_loss}
> torch.save(state, '/content/drive/MyDrive/Bachelor/CViT/weight/deepfakeweights_2.pth')
> test(model)
> return train_loss,train_accu,val_loss,val_accu, min_loss
> ```

Hello @Yasmineldemery,

Can you try these options: 
    `model.load_state_dict(checkpoint['state_dict'])` or 
    `model.load_state_dict(checkpoint['state_dict'], strict=False)`
Have you initialized the model correctly? If you didn't initialize the model correctly, or if you have modified the model architecture after training, such problems might arise. Let me know your results.

**Comment by Yasmineldemery** [comment]
@erprogs
Thanks a lot 
I tried 
model.load_state_dict(checkpoint['state_dict'], strict=False)
and it worked just fine.
and No i haven't changed anything in the model and it was working fine on ur weights file

**Comment by erprogs** [comment]
> 
> 
> Hi, I am running your code for learning.
> 
> > And for question 1, I made some test.
> 
> when I modify this line of code: `filenames = sorted([x for x in os.listdir(sample) if x[-4:] == ".mp4"])` to ` filenames = sorted([x for x in os.listdir(sample) if x[-4:] == ".mp4"])[n:n+1]` (n = 0 to 1)， it all works without any bug. That means it's ok for every video.
> 
> And I found when I modify ` num_workers = N`, the code occurs Segmentation fault after N-th video.
> For example, when I set `num_workers = 9` and run cvit_prediction.py:
> ![sendpix0](https://user-images.githubusercontent.com/82205987/120320783-248ecd00-c315-11eb-86e6-7db31338dd6f.jpg)
> 
> > For qusetion 2, I know it works when I use `checkpoint = torch.load('/content/drive/MyDrive/Bachelor/CViT/weight/deepfake_cvit_gpu_inference_ep_50.pth') `.
> > However, what should I do if I want to train my own net?  I met the same problem when I use ` deepfake_cvit_gpu_ep_50.pth`.

Hello @yeaars,
1. Thank you for testing question 1. You are right. I think the reason for this is the cvit_prediction.py code uses `ThreadPoolExecutor` which uses thread to load multiple videos in parallel. When you set the `num_wokers>0`, it will create a sub-process which will create a resource conflict with threads already handling the videos. An easier solution that I can think of for now is to replace the `predict_on_video()` code with a normal for loop. 
I think this might work. I haven't tested it.
```
def predict_on_video(dfdc_filenames):  
    predictions = []  
    for filename in dfdc_filenames:  
        decCViT = predict(os.path.join(sample, filename), tresh, mtcnn)  
        predictions.append(decCViT)  

    return list(predictions)
```

2. To train your net, you can use cvit_train.py. You can use the face extraction code to extract face regions as we did. The model requires a lot of face images. To train our model, we used 162,174 face images, so If you need to replicate our result or even get a superior model, you might need to extract more than ours. Also, One thing we noticed during training is having a lot of data might no be good for the model. For example, we had 250,000 image sets that we used but, the model was not learning that much. No matter what we did, the model can't just learn from the images. So we settled on our current dataset. After you have extracted the faces, select your face images carefully and make them diverse. Happy training!

**Comment by erprogs** [comment]
@Yasmineldemery,

That's Great!

**Comment by erprogs** [comment]
@18590286257,
As a solution, you might need to replace the code with the one I have provided in my earlier answer  (`predict_on_video(dfdc_filenames)`).
Thank you for the kind words. Glad I helped.

**Comment by yeaars** [comment]
Thanks a lot for your amazing work and patient reply! 
It helps me learn a lot.

**Comment by erprogs** [comment]
@yeaars,
Thank you!.
