### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by wasim004** [erprogs/CViT#8]
Hi,
This error i am getting.
FileNotFoundError: [Errno 2] No such file or directory: 'weight/deepfake_cvit_gpu_inference_ep_50.pth'

Thanks!

**Comment by erprogs** [comment]
Hi wasim004,
You can find the model weights from here: [link to weights](https://github.com/erprogs/CViT/releases/tag/v1.0)
After downloading the files, place them in the weight's folder.
